# Generated by Django 3.2.12 on 2022-05-11 23:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=' ', max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(default=datetime.datetime(2022, 5, 11, 19, 35, 46, 421666))),
                ('fecha_fin', models.DateField(default=datetime.datetime(2022, 7, 10, 19, 35, 46, 421666))),
                ('backlog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backlog.backlog')),
                ('usuarios', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
