# Generated by Django 3.2.12 on 2022-05-12 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20220511_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='backlog',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2022, 7, 10, 20, 36, 21, 985074)),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 20, 36, 21, 985074)),
        ),
    ]
