# Generated by Django 3.2.12 on 2022-06-16 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_auto_20220615_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2022, 8, 14, 21, 8, 52, 914570)),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2022, 6, 15, 21, 8, 52, 914570)),
        ),
    ]
