# Generated by Django 3.2.12 on 2022-07-04 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0016_auto_20220702_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.PositiveIntegerField(choices=[(0, 'Pendiente'), (1, 'En curso'), (2, 'Finalizado')], default=0),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2022, 9, 2, 20, 16, 28, 817644)),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 20, 16, 28, 817630)),
        ),
    ]
