# Generated by Django 4.0.2 on 2022-03-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0003_auto_20220308_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permiso',
            name='tipo',
        ),
    ]
