# Generated by Django 3.2.12 on 2022-05-12 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20220511_2036'),
        ('backlog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backlog',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='backlog',
            name='proyecto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto'),
        ),
    ]
