# Generated by Django 3.2.12 on 2022-05-12 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20220511_2044'),
        ('backlog', '0002_auto_20220511_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='proyecto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto'),
        ),
    ]
