# Generated by Django 3.2.12 on 2022-06-16 01:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0004_auto_20220609_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='comentario',
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(default=' ', max_length=50)),
                ('descripcion', models.TextField()),
                ('estado', models.PositiveIntegerField(choices=[(2, 'Pendiente'), (1, 'Asignado'), (0, 'Finalizado')])),
                ('fecha', models.DateField(default=datetime.datetime(2022, 6, 15, 21, 8, 53, 42578))),
                ('userstory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backlog.userstory')),
            ],
        ),
    ]
