# Generated by Django 3.2.12 on 2022-06-23 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0005_auto_20220615_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='estado',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 22, 22, 4, 36, 612317)),
        ),
    ]
