# Generated by Django 3.2.12 on 2022-06-29 00:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0009_auto_20220628_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 29, 0, 39, 58, 324561)),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='backlog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backlog.backlog'),
        ),
    ]
