# Generated by Django 3.2.12 on 2022-07-01 05:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0001_initial'),
        ('backlog', '0011_auto_20220629_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 7, 1, 5, 48, 40, 582306)),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sprint.sprint'),
        ),
    ]
