# Generated by Django 3.2.12 on 2022-07-02 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0012_auto_20220701_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='estado',
            field=models.PositiveIntegerField(choices=[(2, 'Pendiente'), (1, 'En curso'), (0, 'Finalizado')], default=2),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 7, 2, 1, 21, 29, 203235)),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='estado',
            field=models.PositiveIntegerField(choices=[(2, 'Pendiente'), (1, 'En curso'), (0, 'Finalizado')], default=2),
        ),
    ]
