# Generated by Django 3.2.12 on 2022-07-02 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0013_auto_20220702_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='estado',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 7, 2, 1, 24, 42, 818533)),
        ),
    ]
