# Generated by Django 3.2.12 on 2022-07-04 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0014_auto_20220702_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 20, 16, 28, 819053)),
        ),
    ]
