# Generated by Django 3.2.12 on 2022-03-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0004_remove_permiso_tipo'),
        ('usuarios', '0002_auto_20220308_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(to='rol.Rol'),
        ),
    ]
